plugins {
    id 'groovy'
    id 'eclipse'
    id 'application'
}

version = 0.1

application {
    mainClass = "org.numerals.Console"
}

defaultTasks 'clean', 'build'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.apache.groovy', name: 'groovy', version: '5.1.0'
    testImplementation platform('org.junit:junit-bom:5.14.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
